### ISSUE TITLE
为什么新版的登录以后开始答题就没反应了呢？

### ISSUE THREAD

**Issue by zcsjyl** [Lcmasdf/auto_exam#4]
答测试题目没有问题，但配置好了账号，登录以后开始报错

Traceback (most recent call last):
  File "D:\XCTOOL\code_py\auto_exam-master\main.py", line 24, in <module>
    easy_exam.do_quiz()
  File "D:\XCTOOL\code_py\auto_exam-master\auto_exam.py", line 118, in do_quiz
    self.__do_exam(driver)
  File "D:\XCTOOL\code_py\auto_exam-master\auto_exam.py", line 185, in __do_exam
    prob = self.__get_question(driver, i)
  File "D:\XCTOOL\code_py\auto_exam-master\auto_exam.py", line 158, in __get_question
    items = questions[index].text.split('\n')
IndexError: list index out of range

**Comment by Lcmasdf** [comment]
造成这个问题的原因是正式答题时获取题目的xpath与测试答题时的xpath不同。

目前这个bug已经修正，感谢反馈
